name: CICD Pipeline

on:
  push:
    branches-ignore:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup nodejs environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependancies
        run: npm install

      - name: Build Job
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true
    environment:
      name: ${{ github.base_ref == 'dev' && 'DEV' || 'PROD'  }}
      url: http://localhost:8080/

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Deploy to Azure
        run: |
          echo ${{ vars.TEST_VARIABLE }}
          echo ${{ secrets.TEST_SECRET }}
