name: Main branch Build and Deployment
 
on:
  push:
    branches: ["main", "cicdtest/main"]
    paths-ignore:
      - 'github/**'
  pull_request:
    branches: ["main", "cicdtest/main"]
    # types: [opened,synchronize,closed]
    paths-ignore:
      - '.github/**'
 
env:
  AZURE_WEBAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  AZURE_WEBAPP_NAME: sonyxyzfrontend-test # set this to your application's name
defaults:
  run:
    shell: bash
 
jobs:
 
  PR_check: #This job triggered by PUSH and PR(open, sync) event
    name: PR_check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.8]  # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
    steps:
      - name: PR check Running
  Web_app_deploy:  #This job triggered by PUSH event
    name: Deploy WebApp
    runs-on: ubuntu-latest
    needs: PR_check
    if: (github.ref == 'refs/heads/main') && (github.event_name == 'push')
    steps:
      - name: wait time for testing. 3 mins  # testing with wait time
        run: |
          echo "Sleeping for 1 mins"
          sleep 60s

 
  static_app_preview: #This job triggered by PR event
    runs-on: ubuntu-latest
    if: (github.event.pull_request.base.ref == 'refs/heads/main') && github.event_name == 'pull_request'
    steps:
       - name: testing
         run: echo "Running"

  static_app_deploy: #This job triggered by PUSH event
    runs-on: ubuntu-latest
    needs: PR_check
    if: (github.ref == 'refs/heads/main') && (github.event_name == 'push')
    steps:
      - name: wait time for testing. 3 mins # testing with wait time
        run: sleep 180s
      - uses: actions/checkout@v3


     
